name: Electron CI

on:
    push:
      branches: [ "mobile" ]
    pull_request:
      branches: [ "mobile" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies  
        run: yarn

      - name: Build React app
        run: npm run build
              
      - name: Fix path for electron
        run: yarn fix:path

      - name: Install Electron Packager
        run: npm install electron-packager -g

      - name: Package Electron app for Windows
        run: |
          npx electron-packager . MyApp --platform=win32 --arch=x64 --out=dist --overwrite
        env:
          NODE_ENV: production

      - name: Create zip archive
        run: zip -r MyApp-windows.zip dist/MyApp-win32-x64/
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-windows
          path: MyApp-windows.zip
